version: "3.9"

services:
  app:
    build: .
    container_name: credit_simulator
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
