version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - INIT_SCRIPTS_PATH=/etc/localstack/init
    volumes:
      - ./localstack-data:/var/lib/localstack
      - ./localstack_tmp:/tmp/localstack_tmp
      - ./init-scripts:/etc/localstack/init

  app:
    build: backend
    container_name: credit_simulator
    ports:
      - "8000:8000"
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - USE_LOCALSTACK=true
      - POETRY_VIRTUALENVS_CREATE=false
    volumes:
      - .:/app
      - ./localstack-data:/tmp/localstack/data  # Acesso à mesma pasta de dados da localstack, se necessário
    working_dir: /app
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
