# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/health
Accept: application/json

###

POST http://127.0.0.1:8000/simulate
Content-Type: application/json

{
  "loan_amount": 10000,
  "birth_date": "1990-05-15",
  "months": 12
}
